# Site settings
title: ðŸ°k4ke
logo: /assets/cake.jpg/
email: k4ke@korea.ac.kr
description: Dialog Systems and Reinforcement Learning.
# > # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.

baseurl: "https://jeiyoon.github.io/k4ke" # the subpath of your site, e.g. /blog/
url: "https://jeiyoon.github.io/k4ke" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username: jeiyoon
permalink: /:year/:month/:day/:title/
# this is the url root of the view source link on the footer page.
viewsourceroot: https://github.com/Jeiyoon/k4ke/blob/master/
# this is the url root of the create page link on the footer page.
newsourceroot: https://github.com/Jeiyoon/k4ke/new/master
#########################################
# for duoshuo.com commenting system, uncomment following line if you do not want to include duoshuo.com. 
#duoshuo_shortname: lixizhi
#duoshuo_url: "http://lixizhi.github.io"
# disqus.com commenting system. please note that it is exclusive with duoshuo.com
disqus_shortname: https-jeiyoon-github-io-k4ke
disqus_url: "https://jeiyoon.github.io/k4ke"
#########################################

# Build settings
markdown: kramdown

# highlight
# highlighter: pygments
# highlighter: rouge
# highlighter: false
